### ISSUE TITLE
How to User moodle-auth_shibbuncif

### ISSUE THREAD

**Issue by pexpert9** [appalachianstate/moodle-auth_shibbuncif#1]
How to Use this Plugin .... 

1. Flow of Authentication Flow
2. What is URL Pattern 
3. Is request is Forward to ... (A==>B(Verification) and then B==>A(Confirmation)).

A --> Moodle One
B --> Moodle Two

**Comment by woolardfa** [comment]
This is a customized Shibboleth authentication plugin tailored for use with one particular identity federation, UNC. You will have little use for it, as it provides nothing beyond what the built-in Shibboleth auth module does.
